version: "3.5"
services:
  postgres:
    image: postgres:15
    container_name: sensormanagerdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sensor_manager_network
    volumes:
      - sensor_manager_db:/var/lib/postgresql/data
    restart: always

  sensor-manager-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sensor-manager-api:0.1.0
    networks:
      - sensor_manager_network
    ports:
      - 8080:8080
      
volumes:
  sensor_manager_db:

networks:
  sensor_manager_network:
    driver: bridge