version: "3.5"
services:
  postgres:
    image: postgres:15
    container_name: sensormanagerdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - sensor_manager_network
    volumes:
      - sensor_manager_db:/var/lib/postgresql/data
    restart: always

volumes:
  sensor_manager_db:

networks:
  sensor_manager_network:
    driver: bridge