name: Publishing

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Image name MUST have a pattern like <org_name_lowercase>/<repo_name_lowercase>
  IMAGE_NAME: hpcmonitoring/sensor-manager-api
  IMAGE_TAG: 0.1.0
  # username login to ghcr MUST be organization's name in lower case
  ORG_USERNAME: hpcmonitoring

permissions:
  packages: write

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Will add envs later (if necessary) 
      - name: Set up env file
        run: |
          echo > .env.production

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORG_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # - name: Log into registry ${{ env.REGISTRY }}
      #   run: |
      #     export GHCR_PASS=${{ secrets.GITHUB_TOKEN }}
      #     echo $GHCR_PASS | docker login ${{ env.REGISTRY }} -u ${{ env.ORG_USERNAME }} --password-stdin

      # - name: Build
      #   run: |
      #     docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # - name: Publish
      #   run: |
      #     docker image tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     docker image push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # - name: Cleanup
      #   run: |
      #     rm -f /home/runner/.docker/config.json
      #     docker logout ghcr.io
