name: CI

on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Set up env file
        run: |
          echo > .env.production
          echo POSTGRES_URL=${{ env.POSTGRES_URL }} > .env.production
          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env.production
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.production
          echo CORS_WHITE_LIST=${{ vars.CORS_WHITE_LIST }} >> .env.production

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn lint && yarn test

      - name: Build
        run: yarn build
