name: CI

on:
  pull_request:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: bkhpc/sensor-manager/core

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      # Will add envs later (if necessary) 
      - name: Set up env file
        run: |
          echo > .env.production
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest
      
      # TODO: ssh to a machine which is chosen to be host server and pull image from cloud to deploy
